name: ubunturdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        default: 'paste your code here'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m ash && sudo adduser ash sudo && echo 'ash:ash' | sudo chpasswd
     
    - name: Installing Desktop Environment (wait for 10 min)
      run: sudo apt update && sudo apt install -y expect ubuntu-desktop xfce4 xfce4-goodies

    - name: Installing Google Chrome Headless and Dependencies
      run: |
            sudo useradd -m Ubuntu 
            sudo adduser Ubuntu sudo
            echo 'Ubuntu:1234' | sudo chpasswd
            sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
            sudo apt-get update
            sudo apt-get install -y xfce4-terminal
            
            # Download and install Chrome Remote Desktop
            wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
            sudo dpkg --install chrome-remote-desktop_current_amd64.deb || true
            sudo apt-get install -f -y  # Fix missing dependencies

            # Set up the desktop environment for CRD
            sudo DEBIAN_FRONTEND=noninteractive \
            apt install --assume-yes xfce4 desktop-base
            echo "exec /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session
            sudo systemctl disable lightdm.service

            # Download and install Google Chrome
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg --install google-chrome-stable_current_amd64.deb || sudo apt install --assume-yes --fix-broken

            # Additional utilities
            sudo apt install -y python3-pip xvfb nautilus nano
            pip3 install nbformat gdown pika

            # Install Visual Studio Code
            wget -O code.deb https://code.visualstudio.com/sha/download\?build\=stable\&os\=linux-deb-x64
            sudo dpkg --install code.deb || sudo apt install --assume-yes --fix-broken

            # Set up NVM and Node.js
            wget https://raw.githubusercontent.com/creationix/nvm/master/install.sh
            bash install.sh
            source ~/.profile

            # Add user to chrome-remote-desktop group
            sudo adduser Ubuntu chrome-remote-desktop

    - name: Generate setup script
      run: |
           echo "#!/bin/bash" > setup.sh
           echo "${{ github.event.inputs.auth }}" >> setup.sh
           chmod +x setup.sh

    - name: Initialize Chrome Remote Desktop
      run: |
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "123456\r"
           expect "Enter the same PIN again: "
           send "123456\r"
           expect eof
           '

    - name: SSH tunnel over ngrok
      uses: joshlarsen/ssh-tunnel-action@v1.2
