name: Setup Linux RDP with Chrome Remote Desktop

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  setup-rdp:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget

      - name: Install Chrome Remote Desktop
        run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo apt install -y ./chrome-remote-desktop_current_amd64.deb

      - name: Install Desktop Environment (XFCE)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies

      - name: Create User Account for RDP
        run: |
          sudo useradd -m -s /bin/bash runner  # Create a new user 'runner'
          echo 'runner2:runner1234' | sudo chpasswd  # Set the password for the user

      - name: Configure Chrome Remote Desktop
        run: |
          # Start Chrome Remote Desktop with the specified code
          DISPLAY= /opt/google/chrome-remote-desktop/start-host \
          --code="4/0AVG7fiQQDfXW7218mkh0v-r374xm2IPIax2K_JM_eX_tDRJmTGhUFY-NGPlYiaGZCa8FzA" \
          --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
          --name="$(hostname)" \
          --pin="123456" &  # Set the PIN

      - name: Enable Firewall Rule for RDP (if applicable)
        run: |
          sudo ufw allow 3389/tcp  # RDP Port

      - name: Keep RDP Alive
        run: |
          while true; do
            sleep 60  # Keep the job alive
          done
